---
title: "DispersalTrees"
author: "Camille"
date: "1/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Read Data}
setwd("/Users/camilledesisto/Documents/GitHub/FaunalDegradationABG/HelperScripts")
library(ggpubr)

tdat_frug2_observed <- read.csv("~/Documents/GitHub/FaunalDegradationABG/SummaryOutputs/tdat_frug2_observed.csv")
tree_dat_observed <- tdat_frug2_observed %>% select(meanWD, D, AGB, DispersedBinary, ele, ape, ceph, monkey, smam, ele2, ape2, ceph2, monkey2, smam2)

tdat_frug2_imputed <- read.csv("~/Documents/GitHub/FaunalDegradationABG/SummaryOutputs/tdat_frug2_imputed.csv")
tree_dat_imputed <- tdat_frug2_imputed %>% select(meanWD, D, AGB, DispersedBinary, ele, ape, ceph, monkey, smam ,ele2, ape2, ceph2, monkey2, smam2)

```


```{r Means and CIs- Asuming Compensation- Dispered Plants}
library(BSDA)

#total
total_agb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$DispersedBinary==1])
total_agb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_agb_ci <- total_agb_ci1$conf.int
total_agb_ci_l <- total_agb_ci[1]
total_agb_ci_u <- total_agb_ci[2]

total_d <- mean(tree_dat_imputed$D[tree_dat_imputed$DispersedBinary==1])
total_d_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_d_ci <- total_d_ci1$conf.int
total_d_ci_l <-total_d_ci[1]
total_d_ci_u <-total_d_ci[2]

total_wd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$DispersedBinary==1])
total_wd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_wd_ci <- total_wd_ci1$conf.int
total_wd_ci_l <- total_wd_ci[1]
total_wd_ci_u <- total_wd_ci[2]

total_agb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$DispersedBinary==1])
total_agb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_agb_ci_og <- total_agb_ci1_og$conf.int
total_agb_ci_og_l <-total_agb_ci_og[1]
total_agb_ci_og_u <-total_agb_ci_og[2]

total_d_og <- mean(tree_dat_observed$D[tree_dat_observed$DispersedBinary==1])
total_d_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_d_ci_og <- total_d_ci1_og$conf.int
total_d_ci_og_l <- total_d_ci_og[1]
total_d_ci_og_u <- total_d_ci_og[2]

total_wd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$DispersedBinary==1])
total_wd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_wd_ci_og <- total_wd_ci1_og$conf.int
total_wd_ci_og_l <- total_wd_ci_og[1]
total_wd_ci_og_u <- total_wd_ci_og[2]

#elephant
ele_agb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ele==1])
ele_agb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ele==1], sigma.x = 2, conf.level = 0.95)
ele_agb_ci <- ele_agb_ci1$conf.int
ele_agb_ci_l <-ele_agb_ci[1]
ele_agb_ci_u <-ele_agb_ci[2]

ele_d <- mean(tree_dat_imputed$D[tree_dat_imputed$ele==1])
ele_d_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ele==1], sigma.x = 2, conf.level = 0.95)
ele_d_ci <- ele_d_ci1$conf.int
ele_d_ci_l <- ele_d_ci[1]
ele_d_ci_u <- ele_d_ci[2]

ele_wd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ele==1])
ele_wd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ele==1], sigma.x = 2, conf.level = 0.95)
ele_wd_ci <- ele_wd_ci1$conf.int
ele_wd_ci_l <- ele_wd_ci[1]
ele_wd_ci_u <- ele_wd_ci[2]

ele_agb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ele==1])
ele_agb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ele==1], sigma.x = 2, conf.level = 0.95)
ele_agb_ci_og <- ele_agb_ci1_og$conf.int
ele_agb_ci_og_l <- ele_agb_ci_og[1]
ele_agb_ci_og_u <- ele_agb_ci_og[2]

ele_d_og <- mean(tree_dat_observed$D[tree_dat_observed$ele==1])
ele_d_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ele==1], sigma.x = 2, conf.level = 0.95)
ele_d_ci_og <- ele_d_ci1_og$conf.int
ele_d_ci_og_l <- ele_d_ci_og[1]
ele_d_ci_og_u <- ele_d_ci_og[2]

ele_wd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ele==1])
ele_wd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ele==1], sigma.x = 2, conf.level = 0.95)
ele_wd_ci_og <- ele_wd_ci1_og$conf.int
ele_wd_ci_og_l <- ele_wd_ci_og[1]
ele_wd_ci_og_u <- ele_wd_ci_og[2]

#ape
ape_agb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ape==1])
ape_agb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ape==1], sigma.x = 2, conf.level = 0.95)
ape_agb_ci <- ape_agb_ci1$conf.int
ape_agb_ci_l <-ape_agb_ci[1]
ape_agb_ci_u <-ape_agb_ci[2]

ape_d <- mean(tree_dat_imputed$D[tree_dat_imputed$ape==1])
ape_d_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ape==1], sigma.x = 2, conf.level = 0.95)
ape_d_ci <- ape_d_ci1$conf.int
ape_d_ci_l <- ape_d_ci[1]
ape_d_ci_u <- ape_d_ci[2]

ape_wd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ape==1])
ape_wd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ape==1], sigma.x = 2, conf.level = 0.95)
ape_wd_ci <- ape_wd_ci1$conf.int
ape_wd_ci_l <- ape_wd_ci[1]
ape_wd_ci_u <- ape_wd_ci[2]

ape_agb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ape==1])
ape_agb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ape==1], sigma.x = 2, conf.level = 0.95)
ape_agb_ci_og <- ape_agb_ci1_og$conf.int
ape_agb_ci_og_l <-ape_agb_ci_og[1]
ape_agb_ci_og_u <-ape_agb_ci_og[2]

ape_d_og <- mean(tree_dat_observed$D[tree_dat_observed$ape==1])
ape_d_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ape==1], sigma.x = 2, conf.level = 0.95)
ape_d_ci_og <- ape_d_ci1_og$conf.int
ape_d_ci_og_l <- ape_d_ci_og[1]
ape_d_ci_og_u <- ape_d_ci_og[2]

ape_wd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ape==1])
ape_wd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ape==1], sigma.x = 2, conf.level = 0.95)
ape_wd_ci_og <- ape_wd_ci1_og$conf.int
ape_wd_ci_og_l <- ape_wd_ci_og[1]
ape_wd_ci_og_u <- ape_wd_ci_og[2]

#monkey
monkey_agb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$monkey==1])
monkey_agb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$monkey==1], sigma.x = 2, conf.level = 0.95)
monkey_agb_ci <- monkey_agb_ci1$conf.int
monkey_agb_ci_l <- monkey_agb_ci[1]
monkey_agb_ci_u <- monkey_agb_ci[2]

monkey_d <- mean(tree_dat_imputed$D[tree_dat_imputed$monkey==1])
monkey_d_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$monkey==1], sigma.x = 2, conf.level = 0.95)
monkey_d_ci <- monkey_d_ci1$conf.int
monkey_d_ci_l <- monkey_d_ci[1]
monkey_d_ci_u <- monkey_d_ci[2]

monkey_wd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$monkey==1])
monkey_wd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$monkey==1], sigma.x = 2, conf.level = 0.95)
monkey_wd_ci <- monkey_wd_ci1$conf.int
monkey_wd_ci_l <- monkey_wd_ci[1]
monkey_wd_ci_u <- monkey_wd_ci[2]

monkey_agb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$monkey==1])
monkey_agb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$monkey==1], sigma.x = 2, conf.level = 0.95)
monkey_agb_ci_og <- monkey_agb_ci1_og$conf.int
monkey_agb_ci_og_l <- monkey_agb_ci_og[1]
monkey_agb_ci_og_u <- monkey_agb_ci_og[2]

monkey_d_og <- mean(tree_dat_observed$D[tree_dat_observed$monkey==1])
monkey_d_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$monkey==1], sigma.x = 2, conf.level = 0.95)
monkey_d_ci_og <- monkey_d_ci1_og$conf.int
monkey_d_ci_og_l <- monkey_d_ci_og[1]
monkey_d_ci_og_u <- monkey_d_ci_og[2]

monkey_wd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$monkey==1])
monkey_wd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$monkey==1], sigma.x = 2, conf.level = 0.95)
monkey_wd_ci_og <- monkey_wd_ci1_og$conf.int
monkey_wd_ci_og_l <- monkey_wd_ci_og[1]
monkey_wd_ci_og_u <- monkey_wd_ci_og[2]

#smam
smam_agb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$smam==1])
smam_agb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$smam==1], sigma.x = 2, conf.level = 0.95)
smam_agb_ci <- smam_agb_ci1$conf.int
smam_agb_ci_l <- smam_agb_ci[1]
smam_agb_ci_u <- smam_agb_ci[2]

smam_d <- mean(tree_dat_imputed$D[tree_dat_imputed$smam==1])
smam_d_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$smam==1], sigma.x = 2, conf.level = 0.95)
smam_d_ci <- smam_d_ci1$conf.int
smam_d_ci_l <- smam_d_ci[1]
smam_d_ci_u <- smam_d_ci[2]

smam_wd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$smam==1])
smam_wd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$smam==1], sigma.x = 2, conf.level = 0.95)
smam_wd_ci <- smam_wd_ci1$conf.int
smam_wd_ci_l <- smam_wd_ci[1]
smam_wd_ci_u <- smam_wd_ci[2]

smam_agb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$smam==1])
smam_agb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$smam==1], sigma.x = 2, conf.level = 0.95)
smam_agb_ci_og <- smam_agb_ci1_og$conf.int
smam_agb_ci_og_l <- smam_agb_ci_og[1]
smam_agb_ci_og_u <- smam_agb_ci_og[2]

smam_d_og <- mean(tree_dat_observed$D[tree_dat_observed$smam==1])
smam_d_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$smam==1], sigma.x = 2, conf.level = 0.95)
smam_d_ci_og <- smam_d_ci1_og$conf.int
smam_d_ci_og_l <- smam_d_ci_og[1]
smam_d_ci_og_u <- smam_d_ci_og[2]

smam_wd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$smam==1])
smam_wd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$smam==1], sigma.x = 2, conf.level = 0.95)
smam_wd_ci_og <- smam_wd_ci1_og$conf.int
smam_wd_ci_og_l <- smam_wd_ci_og[1]
smam_wd_ci_og_u <- smam_wd_ci_og[2]

#ceph
ceph_agb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ceph==1])
ceph_agb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ceph==1], sigma.x = 2, conf.level = 0.95)
ceph_agb_ci <- ceph_agb_ci1$conf.int
ceph_agb_ci_l <- ceph_agb_ci[1]
ceph_agb_ci_u <- ceph_agb_ci[2]

ceph_d <- mean(tree_dat_imputed$D[tree_dat_imputed$ceph==1])
ceph_d_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ceph==1], sigma.x = 2, conf.level = 0.95)
ceph_d_ci <- ceph_d_ci1$conf.int
ceph_d_ci_l <- ceph_d_ci[1]
ceph_d_ci_u <- ceph_d_ci[2]

ceph_wd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ceph==1])
ceph_wd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ceph==1], sigma.x = 2, conf.level = 0.95)
ceph_wd_ci <- ceph_wd_ci1$conf.int
ceph_wd_ci_l <- ceph_wd_ci[1]
ceph_wd_ci_u <- ceph_wd_ci[2]

ceph_agb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ceph==1])
ceph_agb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ceph==1], sigma.x = 2, conf.level = 0.95)
ceph_agb_ci_og <- ceph_agb_ci1_og$conf.int
ceph_agb_ci_og_l <- ceph_agb_ci_og[1]
ceph_agb_ci_og_u <- ceph_agb_ci_og[2]

ceph_d_og <- mean(tree_dat_observed$D[tree_dat_observed$ceph==1])
ceph_d_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ceph==1], sigma.x = 2, conf.level = 0.95)
ceph_d_ci_og <- ceph_d_ci1_og$conf.int
ceph_d_ci_og_l <- ceph_d_ci_og[1]
ceph_d_ci_og_u <- ceph_d_ci_og[2]

ceph_wd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ceph==1])
ceph_wd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ceph==1], sigma.x = 2, conf.level = 0.95)
ceph_wd_ci_og <- ceph_wd_ci1_og$conf.int
ceph_wd_ci_og_l <- ceph_wd_ci_og[1]
ceph_wd_ci_og_u <- ceph_wd_ci_og[2]

```


```{r Means and CIs- Not Assuming Compensation - Dispered Plants}
library(BSDA)

#total_nr
total_nr_agb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$DispersedBinary==1])
total_nr_agb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_nr_agb_ci <- total_nr_agb_ci1$conf.int
total_nr_agb_ci_l <- total_nr_agb_ci[1]
total_nr_agb_ci_u <- total_nr_agb_ci[2]

total_nr_d <- mean(tree_dat_imputed$D[tree_dat_imputed$DispersedBinary==1])
total_nr_d_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_nr_d_ci <- total_nr_d_ci1$conf.int
total_nr_d_ci_l <-total_nr_d_ci[1]
total_nr_d_ci_u <-total_nr_d_ci[2]

total_nr_wd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$DispersedBinary==1])
total_nr_wd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_nr_wd_ci <- total_nr_wd_ci1$conf.int
total_nr_wd_ci_l <- total_nr_wd_ci[1]
total_nr_wd_ci_u <- total_nr_wd_ci[2]

total_nr_agb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$DispersedBinary==1])
total_nr_agb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_nr_agb_ci_og <- total_nr_agb_ci1_og$conf.int
total_nr_agb_ci_og_l <-total_nr_agb_ci_og[1]
total_nr_agb_ci_og_u <-total_nr_agb_ci_og[2]

total_nr_d_og <- mean(tree_dat_observed$D[tree_dat_observed$DispersedBinary==1])
total_nr_d_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_nr_d_ci_og <- total_nr_d_ci1_og$conf.int
total_nr_d_ci_og_l <- total_nr_d_ci_og[1]
total_nr_d_ci_og_u <- total_nr_d_ci_og[2]

total_nr_wd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$DispersedBinary==1])
total_nr_wd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$DispersedBinary==1], sigma.x = 2, conf.level = 0.95)
total_nr_wd_ci_og <- total_nr_wd_ci1_og$conf.int
total_nr_wd_ci_og_l <- total_nr_wd_ci_og[1]
total_nr_wd_ci_og_u <- total_nr_wd_ci_og[2]

#elephant
ele_nragb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ele2==1])
ele_nragb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ele2==1], sigma.x = 2, conf.level = 0.95)
ele_nragb_ci <- ele_nragb_ci1$conf.int
ele_nragb_ci_l <-ele_nragb_ci[1]
ele_nragb_ci_u <-ele_nragb_ci[2]

ele_nrd <- mean(tree_dat_imputed$D[tree_dat_imputed$ele2==1])
ele_nrd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ele2==1], sigma.x = 2, conf.level = 0.95)
ele_nrd_ci <- ele_nrd_ci1$conf.int
ele_nrd_ci_l <- ele_nrd_ci[1]
ele_nrd_ci_u <- ele_nrd_ci[2]

ele_nrwd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ele2==1])
ele_nrwd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ele2==1], sigma.x = 2, conf.level = 0.95)
ele_nrwd_ci <- ele_nrwd_ci1$conf.int
ele_nrwd_ci_l <- ele_nrwd_ci[1]
ele_nrwd_ci_u <- ele_nrwd_ci[2]

ele_nragb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ele2==1])
ele_nragb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ele2==1], sigma.x = 2, conf.level = 0.95)
ele_nragb_ci_og <- ele_nragb_ci1_og$conf.int
ele_nragb_ci_og_l <- ele_nragb_ci_og[1]
ele_nragb_ci_og_u <- ele_nragb_ci_og[2]

ele_nrd_og <- mean(tree_dat_observed$D[tree_dat_observed$ele2==1])
ele_nrd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ele2==1], sigma.x = 2, conf.level = 0.95)
ele_nrd_ci_og <- ele_nrd_ci1_og$conf.int
ele_nrd_ci_og_l <- ele_nrd_ci_og[1]
ele_nrd_ci_og_u <- ele_nrd_ci_og[2]

ele_nrwd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ele2==1])
ele_nrwd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ele2==1], sigma.x = 2, conf.level = 0.95)
ele_nrwd_ci_og <- ele_nrwd_ci1_og$conf.int
ele_nrwd_ci_og_l <- ele_nrwd_ci_og[1]
ele_nrwd_ci_og_u <- ele_nrwd_ci_og[2]

#ape
ape_nragb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ape2==1])
ape_nragb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ape2==1], sigma.x = 2, conf.level = 0.95)
ape_nragb_ci <- ape_nragb_ci1$conf.int
ape_nragb_ci_l <-ape_nragb_ci[1]
ape_nragb_ci_u <-ape_nragb_ci[2]

ape_nrd <- mean(tree_dat_imputed$D[tree_dat_imputed$ape2==1])
ape_nrd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ape2==1], sigma.x = 2, conf.level = 0.95)
ape_nrd_ci <- ape_nrd_ci1$conf.int
ape_nrd_ci_l <- ape_nrd_ci[1]
ape_nrd_ci_u <- ape_nrd_ci[2]

ape_nrwd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ape2==1])
ape_nrwd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ape2==1], sigma.x = 2, conf.level = 0.95)
ape_nrwd_ci <- ape_nrwd_ci1$conf.int
ape_nrwd_ci_l <- ape_nrwd_ci[1]
ape_nrwd_ci_u <- ape_nrwd_ci[2]

ape_nragb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ape2==1])
ape_nragb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ape2==1], sigma.x = 2, conf.level = 0.95)
ape_nragb_ci_og <- ape_nragb_ci1_og$conf.int
ape_nragb_ci_og_l <-ape_nragb_ci_og[1]
ape_nragb_ci_og_u <-ape_nragb_ci_og[2]

ape_nrd_og <- mean(tree_dat_observed$D[tree_dat_observed$ape2==1])
ape_nrd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ape2==1], sigma.x = 2, conf.level = 0.95)
ape_nrd_ci_og <- ape_nrd_ci1_og$conf.int
ape_nrd_ci_og_l <- ape_nrd_ci_og[1]
ape_nrd_ci_og_u <- ape_nrd_ci_og[2]

ape_nrwd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ape2==1])
ape_nrwd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ape2==1], sigma.x = 2, conf.level = 0.95)
ape_nrwd_ci_og <- ape_nrwd_ci1_og$conf.int
ape_nrwd_ci_og_l <- ape_nrwd_ci_og[1]
ape_nrwd_ci_og_u <- ape_nrwd_ci_og[2]

#monkey
monkey_nragb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$monkey2==1])
monkey_nragb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$monkey2==1], sigma.x = 2, conf.level = 0.95)
monkey_nragb_ci <- monkey_nragb_ci1$conf.int
monkey_nragb_ci_l <- monkey_nragb_ci[1]
monkey_nragb_ci_u <- monkey_nragb_ci[2]

monkey_nrd <- mean(tree_dat_imputed$D[tree_dat_imputed$monkey2==1])
monkey_nrd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$monkey2==1], sigma.x = 2, conf.level = 0.95)
monkey_nrd_ci <- monkey_nrd_ci1$conf.int
monkey_nrd_ci_l <- monkey_nrd_ci[1]
monkey_nrd_ci_u <- monkey_nrd_ci[2]

monkey_nrwd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$monkey2==1])
monkey_nrwd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$monkey2==1], sigma.x = 2, conf.level = 0.95)
monkey_nrwd_ci <- monkey_nrwd_ci1$conf.int
monkey_nrwd_ci_l <- monkey_nrwd_ci[1]
monkey_nrwd_ci_u <- monkey_nrwd_ci[2]

monkey_nragb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$monkey2==1])
monkey_nragb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$monkey2==1], sigma.x = 2, conf.level = 0.95)
monkey_nragb_ci_og <- monkey_nragb_ci1_og$conf.int
monkey_nragb_ci_og_l <- monkey_nragb_ci_og[1]
monkey_nragb_ci_og_u <- monkey_nragb_ci_og[2]

monkey_nrd_og <- mean(tree_dat_observed$D[tree_dat_observed$monkey2==1])
monkey_nrd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$monkey2==1], sigma.x = 2, conf.level = 0.95)
monkey_nrd_ci_og <- monkey_nrd_ci1_og$conf.int
monkey_nrd_ci_og_l <- monkey_nrd_ci_og[1]
monkey_nrd_ci_og_u <- monkey_nrd_ci_og[2]

monkey_nrwd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$monkey2==1])
monkey_nrwd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$monkey2==1], sigma.x = 2, conf.level = 0.95)
monkey_nrwd_ci_og <- monkey_nrwd_ci1_og$conf.int
monkey_nrwd_ci_og_l <- monkey_nrwd_ci_og[1]
monkey_nrwd_ci_og_u <- monkey_nrwd_ci_og[2]

#smam
smam_nragb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$smam2==1])
#smam_nragb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$smam2==1], sigma.x = 2, conf.level = 0.95)
smam_nragb_ci <- 0
smam_nragb_ci_l <- 0
smam_nragb_ci_u <- 0

smam_nrd <- mean(tree_dat_imputed$D[tree_dat_imputed$smam2==1])
#smam_nrd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$smam2==1], sigma.x = 2, conf.level = 0.95)
smam_nrd_ci <- 0
smam_nrd_ci_l <- 0
smam_nrd_ci_u <- 0

smam_nrwd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$smam2==1])
#smam_nrwd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$smam2==1], sigma.x = 2, conf.level = 0.95)
smam_nrwd_ci <- 0
smam_nrwd_ci_l <- 0
smam_nrwd_ci_u <- 0

smam_nragb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$smam2==1])
#smam_nragb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$smam2==1], sigma.x = 2, conf.level = 0.95)
smam_nragb_ci_og <- 0
smam_nragb_ci_og_l <- 0
smam_nragb_ci_og_u <- 0

smam_nrd_og <- mean(tree_dat_observed$D[tree_dat_observed$smam2==1])
#smam_nrd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$smam2==1], sigma.x = 2, conf.level = 0.95)
smam_nrd_ci_og <- 0
smam_nrd_ci_og_l <- 0
smam_nrd_ci_og_u <- 0

smam_nrwd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$smam2==1])
#smam_nrwd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$smam2==1], sigma.x = 2, conf.level = 0.95)
smam_nrwd_ci_og <- 0
smam_nrwd_ci_og_l <- 0
smam_nrwd_ci_og_u <- 0

#ceph
ceph_nragb <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ceph2==1])
ceph_nragb_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ceph2==1], sigma.x = 2, conf.level = 0.95)
ceph_nragb_ci <- ceph_nragb_ci1$conf.int
ceph_nragb_ci_l <- ceph_nragb_ci[1]
ceph_nragb_ci_u <- ceph_nragb_ci[2]

ceph_nrd <- mean(tree_dat_imputed$D[tree_dat_imputed$ceph2==1])
ceph_nrd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ceph2==1], sigma.x = 2, conf.level = 0.95)
ceph_nrd_ci <- ceph_nrd_ci1$conf.int
ceph_nrd_ci_l <- ceph_nrd_ci[1]
ceph_nrd_ci_u <- ceph_nrd_ci[2]

ceph_nrwd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ceph2==1])
#ceph_nrwd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ceph2==1], sigma.x = 2, conf.level = 0.95)
ceph_nrwd_ci <- 0.6651687
ceph_nrwd_ci_l <- 0.6651687
ceph_nrwd_ci_u <- 0.6651687

ceph_nragb_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ceph2==1])
ceph_nragb_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ceph2==1], sigma.x = 2, conf.level = 0.95)
ceph_nragb_ci_og <- ceph_nragb_ci1_og$conf.int
ceph_nragb_ci_og_l <- ceph_nragb_ci_og[1]
ceph_nragb_ci_og_u <- ceph_nragb_ci_og[2]

ceph_nrd_og <- mean(tree_dat_observed$D[tree_dat_observed$ceph2==1])
ceph_nrd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ceph2==1], sigma.x = 2, conf.level = 0.95)
ceph_nrd_ci_og <- ceph_nrd_ci1_og$conf.int
ceph_nrd_ci_og_l <- ceph_nrd_ci_og[1]
ceph_nrd_ci_og_u <- ceph_nrd_ci_og[2]

ceph_nrwd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ceph2==1])
#ceph_nrwd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ceph2==1], sigma.x = 2, conf.level = 0.95)
ceph_nrwd_ci_og <- 0.6651687
ceph_nrwd_ci_og_l <- 0.6651687
ceph_nrwd_ci_og_u <- 0.6651687

```


```{r Means and CIs- Assuming Redundancy - Non Dispered Plants}
library(BSDA)

#total
total_agb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$DispersedBinary==0])
total_agb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_agb_nd_ci<- total_agb_nd_ci1$conf.int
total_agb_nd_ci_l <- total_agb_nd_ci[1]
total_agb_nd_ci_u <- total_agb_nd_ci[2]

total_d_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$DispersedBinary==0])
total_d_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_d_nd_ci <- total_d_nd_ci1$conf.int
total_d_nd_ci_l <-total_d_nd_ci[1]
total_d_nd_ci_u <-total_d_nd_ci[2]

total_wd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$DispersedBinary==0])
total_wd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_wd_nd_ci <- total_wd_nd_ci1$conf.int
total_wd_nd_ci_l <- total_wd_nd_ci[1]
total_wd_nd_ci_u <- total_wd_nd_ci[2]

total_agb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$DispersedBinary==0])
total_agb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_agb_nd_ci_og <- total_agb_nd_ci1_og$conf.int
total_agb_nd_ci_og_l <-total_agb_nd_ci_og[1]
total_agb_nd_ci_og_u <-total_agb_nd_ci_og[2]

total_d_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$DispersedBinary==0])
total_d_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_d_nd_ci_og <- total_d_nd_ci1_og$conf.int
total_d_nd_ci_og_l <- total_d_nd_ci_og[1]
total_d_nd_ci_og_u <- total_d_nd_ci_og[2]

total_wd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$DispersedBinary==0])
total_wd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_wd_nd_ci_og <- total_wd_nd_ci1_og$conf.int
total_wd_nd_ci_og_l <- total_wd_nd_ci_og[1]
total_wd_nd_ci_og_u <- total_wd_nd_ci_og[2]

#elephant
ele_agb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ele==0])
ele_agb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ele==0], sigma.x = 2, conf.level = 0.95)
ele_agb_nd_ci <- ele_agb_nd_ci1$conf.int
ele_agb_nd_ci_l <-ele_agb_nd_ci[1]
ele_agb_nd_ci_u <-ele_agb_nd_ci[2]

ele_d_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$ele==0])
ele_d_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ele==0], sigma.x = 2, conf.level = 0.95)
ele_d_nd_ci <- ele_d_nd_ci1$conf.int
ele_d_nd_ci_l <- ele_d_nd_ci[1]
ele_d_nd_ci_u <- ele_d_nd_ci[2]

ele_wd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ele==0])
ele_wd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ele==0], sigma.x = 2, conf.level = 0.95)
ele_wd_nd_ci <- ele_wd_nd_ci1$conf.int
ele_wd_nd_ci_l <- ele_wd_nd_ci[1]
ele_wd_nd_ci_u <- ele_wd_nd_ci[2]

ele_agb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ele==0])
ele_agb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ele==0], sigma.x = 2, conf.level = 0.95)
ele_agb_nd_ci_og <- ele_agb_nd_ci1_og$conf.int
ele_agb_nd_ci_og_l <- ele_agb_nd_ci_og[1]
ele_agb_nd_ci_og_u <- ele_agb_nd_ci_og[2]

ele_d_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$ele==0])
ele_d_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ele==0], sigma.x = 2, conf.level = 0.95)
ele_d_nd_ci_og <- ele_d_nd_ci1_og$conf.int
ele_d_nd_ci_og_l <- ele_d_nd_ci_og[1]
ele_d_nd_ci_og_u <- ele_d_nd_ci_og[2]

ele_wd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ele==0])
ele_wd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ele==0], sigma.x = 2, conf.level = 0.95)
ele_wd_nd_ci_og <- ele_wd_nd_ci1_og$conf.int
ele_wd_nd_ci_og_l <- ele_wd_nd_ci_og[1]
ele_wd_nd_ci_og_u <- ele_wd_nd_ci_og[2]

#ape
ape_agb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ape==0])
ape_agb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ape==0], sigma.x = 2, conf.level = 0.95)
ape_agb_nd_ci <- ape_agb_nd_ci1$conf.int
ape_agb_nd_ci_l <-ape_agb_nd_ci[1]
ape_agb_nd_ci_u <-ape_agb_nd_ci[2]

ape_d_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$ape==0])
ape_d_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ape==0], sigma.x = 2, conf.level = 0.95)
ape_d_nd_ci <- ape_d_nd_ci1$conf.int
ape_d_nd_ci_l <- ape_d_nd_ci[1]
ape_d_nd_ci_u <- ape_d_nd_ci[2]

ape_wd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ape==0])
ape_wd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ape==0], sigma.x = 2, conf.level = 0.95)
ape_wd_nd_ci <- ape_wd_nd_ci1$conf.int
ape_wd_nd_ci_l <- ape_wd_nd_ci[1]
ape_wd_nd_ci_u <- ape_wd_nd_ci[2]

ape_agb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ape==0])
ape_agb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ape==0], sigma.x = 2, conf.level = 0.95)
ape_agb_nd_ci_og <- ape_agb_nd_ci1_og$conf.int
ape_agb_nd_ci_og_l <-ape_agb_nd_ci_og[1]
ape_agb_nd_ci_og_u <-ape_agb_nd_ci_og[2]

ape_d_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$ape==0])
ape_d_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ape==0], sigma.x = 2, conf.level = 0.95)
ape_d_nd_ci_og <- ape_d_nd_ci1_og$conf.int
ape_d_nd_ci_og_l <- ape_d_nd_ci_og[1]
ape_d_nd_ci_og_u <- ape_d_nd_ci_og[2]

ape_wd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ape==0])
ape_wd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ape==0], sigma.x = 2, conf.level = 0.95)
ape_wd_nd_ci_og <- ape_wd_nd_ci1_og$conf.int
ape_wd_nd_ci_og_l <- ape_wd_nd_ci_og[1]
ape_wd_nd_ci_og_u <- ape_wd_nd_ci_og[2]

#monkey
monkey_agb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$monkey==0])
monkey_agb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$monkey==0], sigma.x = 2, conf.level = 0.95)
monkey_agb_nd_ci <- monkey_agb_nd_ci1$conf.int
monkey_agb_nd_ci_l <- monkey_agb_nd_ci[1]
monkey_agb_nd_ci_u <- monkey_agb_nd_ci[2]

monkey_d_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$monkey==0])
monkey_d_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$monkey==0], sigma.x = 2, conf.level = 0.95)
monkey_d_nd_ci <- monkey_d_nd_ci1$conf.int
monkey_d_nd_ci_l <- monkey_d_nd_ci[1]
monkey_d_nd_ci_u <- monkey_d_nd_ci[2]

monkey_wd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$monkey==0])
monkey_wd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$monkey==0], sigma.x = 2, conf.level = 0.95)
monkey_wd_nd_ci <- monkey_wd_nd_ci1$conf.int
monkey_wd_nd_ci_l <- monkey_wd_nd_ci[1]
monkey_wd_nd_ci_u <- monkey_wd_nd_ci[2]

monkey_agb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$monkey==0])
monkey_agb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$monkey==0], sigma.x = 2, conf.level = 0.95)
monkey_agb_nd_ci_og <- monkey_agb_nd_ci1_og$conf.int
monkey_agb_nd_ci_og_l <- monkey_agb_nd_ci_og[1]
monkey_agb_nd_ci_og_u <- monkey_agb_nd_ci_og[2]

monkey_d_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$monkey==0])
monkey_d_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$monkey==0], sigma.x = 2, conf.level = 0.95)
monkey_d_nd_ci_og <- monkey_d_nd_ci1_og$conf.int
monkey_d_nd_ci_og_l <- monkey_d_nd_ci_og[1]
monkey_d_nd_ci_og_u <- monkey_d_nd_ci_og[2]

monkey_wd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$monkey==0])
monkey_wd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$monkey==0], sigma.x = 2, conf.level = 0.95)
monkey_wd_nd_ci_og <- monkey_wd_nd_ci1_og$conf.int
monkey_wd_nd_ci_og_l <- monkey_wd_nd_ci_og[1]
monkey_wd_nd_ci_og_u <- monkey_wd_nd_ci_og[2]

#smam
smam_agb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$smam==0])
smam_agb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$smam==0], sigma.x = 2, conf.level = 0.95)
smam_agb_nd_ci <- smam_agb_nd_ci1$conf.int
smam_agb_nd_ci_l <- smam_agb_nd_ci[1]
smam_agb_nd_ci_u <- smam_agb_nd_ci[2]

smam_d_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$smam==0])
smam_d_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$smam==0], sigma.x = 2, conf.level = 0.95)
smam_d_nd_ci <- smam_d_nd_ci1$conf.int
smam_d_nd_ci_l <- smam_d_nd_ci[1]
smam_d_nd_ci_u <- smam_d_nd_ci[2]

smam_wd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$smam==0])
smam_wd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$smam==0], sigma.x = 2, conf.level = 0.95)
smam_wd_nd_ci <- smam_wd_nd_ci1$conf.int
smam_wd_nd_ci_l <- smam_wd_nd_ci[1]
smam_wd_nd_ci_u <- smam_wd_nd_ci[2]

smam_agb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$smam==0])
smam_agb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$smam==0], sigma.x = 2, conf.level = 0.95)
smam_agb_nd_ci_og <- smam_agb_nd_ci1_og$conf.int
smam_agb_nd_ci_og_l <- smam_agb_nd_ci_og[1]
smam_agb_nd_ci_og_u <- smam_agb_nd_ci_og[2]

smam_d_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$smam==0])
smam_d_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$smam==0], sigma.x = 2, conf.level = 0.95)
smam_d_nd_ci_og <- smam_d_nd_ci1_og$conf.int
smam_d_nd_ci_og_l <- smam_d_nd_ci_og[1]
smam_d_nd_ci_og_u <- smam_d_nd_ci_og[2]

smam_wd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$smam==0])
smam_wd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$smam==0], sigma.x = 2, conf.level = 0.95)
smam_wd_nd_ci_og <- smam_wd_nd_ci1_og$conf.int
smam_wd_nd_ci_og_l <- smam_wd_nd_ci_og[1]
smam_wd_nd_ci_og_u <- smam_wd_nd_ci_og[2]

#ceph
ceph_agb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ceph==0])
ceph_agb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ceph==0], sigma.x = 2, conf.level = 0.95)
ceph_agb_nd_ci <- ceph_agb_nd_ci1$conf.int
ceph_agb_nd_ci_l <- ceph_agb_nd_ci[1]
ceph_agb_nd_ci_u <- ceph_agb_nd_ci[2]

ceph_d_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$ceph==0])
ceph_d_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ceph==0], sigma.x = 2, conf.level = 0.95)
ceph_d_nd_ci <- ceph_d_nd_ci1$conf.int
ceph_d_nd_ci_l <- ceph_d_nd_ci[1]
ceph_d_nd_ci_u <- ceph_d_nd_ci[2]

ceph_wd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ceph==0])
ceph_wd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ceph==0], sigma.x = 2, conf.level = 0.95)
ceph_wd_nd_ci <- ceph_wd_nd_ci1$conf.int
ceph_wd_nd_ci_l <- ceph_wd_nd_ci[1]
ceph_wd_nd_ci_u <- ceph_wd_nd_ci[2]

ceph_agb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ceph==0])
ceph_agb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ceph==0], sigma.x = 2, conf.level = 0.95)
ceph_agb_nd_ci_og <- ceph_agb_nd_ci1_og$conf.int
ceph_agb_nd_ci_og_l <- ceph_agb_nd_ci_og[1]
ceph_agb_nd_ci_og_u <- ceph_agb_nd_ci_og[2]

ceph_d_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$ceph==0])
ceph_d_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ceph==0], sigma.x = 2, conf.level = 0.95)
ceph_d_nd_ci_og <- ceph_d_nd_ci1_og$conf.int
ceph_d_nd_ci_og_l <- ceph_d_nd_ci_og[1]
ceph_d_nd_ci_og_u <- ceph_d_nd_ci_og[2]

ceph_wd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ceph==0])
ceph_wd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ceph==0], sigma.x = 2, conf.level = 0.95)
ceph_wd_nd_ci_og <- ceph_wd_nd_ci1_og$conf.int
ceph_wd_nd_ci_og_l <- ceph_wd_nd_ci_og[1]
ceph_wd_nd_ci_og_u <- ceph_wd_nd_ci_og[2]

```

```{r Means and CIs- Assuming Redundancy - Non Dispered Plants}
library(BSDA)

#total
total_nragb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$DispersedBinary==0])
total_nragb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_nragb_nd_ci<- total_nragb_nd_ci1$conf.int
total_nragb_nd_ci_l <- total_nragb_nd_ci[1]
total_nragb_nd_ci_u <- total_nragb_nd_ci[2]

total_nrd_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$DispersedBinary==0])
total_nrd_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_nrd_nd_ci <- total_nrd_nd_ci1$conf.int
total_nrd_nd_ci_l <-total_nrd_nd_ci[1]
total_nrd_nd_ci_u <-total_nrd_nd_ci[2]

total_nrwd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$DispersedBinary==0])
total_nrwd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_nrwd_nd_ci <- total_nrwd_nd_ci1$conf.int
total_nrwd_nd_ci_l <- total_nrwd_nd_ci[1]
total_nrwd_nd_ci_u <- total_nrwd_nd_ci[2]

total_nragb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$DispersedBinary==0])
total_nragb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_nragb_nd_ci_og <- total_nragb_nd_ci1_og$conf.int
total_nragb_nd_ci_og_l <-total_nragb_nd_ci_og[1]
total_nragb_nd_ci_og_u <-total_nragb_nd_ci_og[2]

total_nrd_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$DispersedBinary==0])
total_nrd_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_nrd_nd_ci_og <- total_nrd_nd_ci1_og$conf.int
total_nrd_nd_ci_og_l <- total_nrd_nd_ci_og[1]
total_nrd_nd_ci_og_u <- total_nrd_nd_ci_og[2]

total_nrwd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$DispersedBinary==0])
total_nrwd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$DispersedBinary==0], sigma.x = 2, conf.level = 0.95)
total_nrwd_nd_ci_og <- total_nrwd_nd_ci1_og$conf.int
total_nrwd_nd_ci_og_l <- total_nrwd_nd_ci_og[1]
total_nrwd_nd_ci_og_u <- total_nrwd_nd_ci_og[2]

#elephant
ele_nragb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ele2==0])
ele_nragb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ele2==0], sigma.x = 2, conf.level = 0.95)
ele_nragb_nd_ci <- ele_nragb_nd_ci1$conf.int
ele_nragb_nd_ci_l <-ele_nragb_nd_ci[1]
ele_nragb_nd_ci_u <-ele_nragb_nd_ci[2]

ele_nrd_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$ele2==0])
ele_nrd_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ele2==0], sigma.x = 2, conf.level = 0.95)
ele_nrd_nd_ci <- ele_nrd_nd_ci1$conf.int
ele_nrd_nd_ci_l <- ele_nrd_nd_ci[1]
ele_nrd_nd_ci_u <- ele_nrd_nd_ci[2]

ele_nrwd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ele2==0])
ele_nrwd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ele2==0], sigma.x = 2, conf.level = 0.95)
ele_nrwd_nd_ci <- ele_nrwd_nd_ci1$conf.int
ele_nrwd_nd_ci_l <- ele_nrwd_nd_ci[1]
ele_nrwd_nd_ci_u <- ele_nrwd_nd_ci[2]

ele_nragb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ele2==0])
ele_nragb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ele2==0], sigma.x = 2, conf.level = 0.95)
ele_nragb_nd_ci_og <- ele_nragb_nd_ci1_og$conf.int
ele_nragb_nd_ci_og_l <- ele_nragb_nd_ci_og[1]
ele_nragb_nd_ci_og_u <- ele_nragb_nd_ci_og[2]

ele_nrd_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$ele2==0])
ele_nrd_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ele2==0], sigma.x = 2, conf.level = 0.95)
ele_nrd_nd_ci_og <- ele_nrd_nd_ci1_og$conf.int
ele_nrd_nd_ci_og_l <- ele_nrd_nd_ci_og[1]
ele_nrd_nd_ci_og_u <- ele_nrd_nd_ci_og[2]

ele_nrwd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ele2==0])
ele_nrwd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ele2==0], sigma.x = 2, conf.level = 0.95)
ele_nrwd_nd_ci_og <- ele_nrwd_nd_ci1_og$conf.int
ele_nrwd_nd_ci_og_l <- ele_nrwd_nd_ci_og[1]
ele_nrwd_nd_ci_og_u <- ele_nrwd_nd_ci_og[2]

#ape
ape_nragb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ape2==0])
ape_nragb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ape2==0], sigma.x = 2, conf.level = 0.95)
ape_nragb_nd_ci <- ape_nragb_nd_ci1$conf.int
ape_nragb_nd_ci_l <-ape_nragb_nd_ci[1]
ape_nragb_nd_ci_u <-ape_nragb_nd_ci[2]

ape_nrd_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$ape2==0])
ape_nrd_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ape2==0], sigma.x = 2, conf.level = 0.95)
ape_nrd_nd_ci <- ape_nrd_nd_ci1$conf.int
ape_nrd_nd_ci_l <- ape_nrd_nd_ci[1]
ape_nrd_nd_ci_u <- ape_nrd_nd_ci[2]

ape_nrwd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ape2==0])
ape_nrwd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ape2==0], sigma.x = 2, conf.level = 0.95)
ape_nrwd_nd_ci <- ape_nrwd_nd_ci1$conf.int
ape_nrwd_nd_ci_l <- ape_nrwd_nd_ci[1]
ape_nrwd_nd_ci_u <- ape_nrwd_nd_ci[2]

ape_nragb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ape2==0])
ape_nragb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ape2==0], sigma.x = 2, conf.level = 0.95)
ape_nragb_nd_ci_og <- ape_nragb_nd_ci1_og$conf.int
ape_nragb_nd_ci_og_l <-ape_nragb_nd_ci_og[1]
ape_nragb_nd_ci_og_u <-ape_nragb_nd_ci_og[2]

ape_nrd_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$ape2==0])
ape_nrd_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ape2==0], sigma.x = 2, conf.level = 0.95)
ape_nrd_nd_ci_og <- ape_nrd_nd_ci1_og$conf.int
ape_nrd_nd_ci_og_l <- ape_nrd_nd_ci_og[1]
ape_nrd_nd_ci_og_u <- ape_nrd_nd_ci_og[2]

ape_nrwd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ape2==0])
ape_nrwd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ape2==0], sigma.x = 2, conf.level = 0.95)
ape_nrwd_nd_ci_og <- ape_nrwd_nd_ci1_og$conf.int
ape_nrwd_nd_ci_og_l <- ape_nrwd_nd_ci_og[1]
ape_nrwd_nd_ci_og_u <- ape_nrwd_nd_ci_og[2]

#monkey
monkey_nragb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$monkey2==0])
monkey_nragb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$monkey2==0], sigma.x = 2, conf.level = 0.95)
monkey_nragb_nd_ci <- monkey_nragb_nd_ci1$conf.int
monkey_nragb_nd_ci_l <- monkey_nragb_nd_ci[1]
monkey_nragb_nd_ci_u <- monkey_nragb_nd_ci[2]

monkey_nrd_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$monkey2==0])
monkey_nrd_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$monkey2==0], sigma.x = 2, conf.level = 0.95)
monkey_nrd_nd_ci <- monkey_nrd_nd_ci1$conf.int
monkey_nrd_nd_ci_l <- monkey_nrd_nd_ci[1]
monkey_nrd_nd_ci_u <- monkey_nrd_nd_ci[2]

monkey_nrwd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$monkey2==0])
monkey_nrwd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$monkey2==0], sigma.x = 2, conf.level = 0.95)
monkey_nrwd_nd_ci <- monkey_nrwd_nd_ci1$conf.int
monkey_nrwd_nd_ci_l <- monkey_nrwd_nd_ci[1]
monkey_nrwd_nd_ci_u <- monkey_nrwd_nd_ci[2]

monkey_nragb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$monkey2==0])
monkey_nragb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$monkey2==0], sigma.x = 2, conf.level = 0.95)
monkey_nragb_nd_ci_og <- monkey_nragb_nd_ci1_og$conf.int
monkey_nragb_nd_ci_og_l <- monkey_nragb_nd_ci_og[1]
monkey_nragb_nd_ci_og_u <- monkey_nragb_nd_ci_og[2]

monkey_nrd_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$monkey2==0])
monkey_nrd_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$monkey2==0], sigma.x = 2, conf.level = 0.95)
monkey_nrd_nd_ci_og <- monkey_nrd_nd_ci1_og$conf.int
monkey_nrd_nd_ci_og_l <- monkey_nrd_nd_ci_og[1]
monkey_nrd_nd_ci_og_u <- monkey_nrd_nd_ci_og[2]

monkey_nrwd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$monkey2==0])
monkey_nrwd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$monkey2==0], sigma.x = 2, conf.level = 0.95)
monkey_nrwd_nd_ci_og <- monkey_nrwd_nd_ci1_og$conf.int
monkey_nrwd_nd_ci_og_l <- monkey_nrwd_nd_ci_og[1]
monkey_nrwd_nd_ci_og_u <- monkey_nrwd_nd_ci_og[2]

#smam
smam_nragb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$smam2==0])
smam_nragb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$smam2==0], sigma.x = 2, conf.level = 0.95)
smam_nragb_nd_ci <- smam_nragb_nd_ci1$conf.int
smam_nragb_nd_ci_l <- smam_nragb_nd_ci[1]
smam_nragb_nd_ci_u <- smam_nragb_nd_ci[2]

smam_nrd_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$smam2==0])
smam_nrd_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$smam2==0], sigma.x = 2, conf.level = 0.95)
smam_nrd_nd_ci <- smam_nrd_nd_ci1$conf.int
smam_nrd_nd_ci_l <- smam_nrd_nd_ci[1]
smam_nrd_nd_ci_u <- smam_nrd_nd_ci[2]

smam_nrwd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$smam2==0])
smam_nrwd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$smam2==0], sigma.x = 2, conf.level = 0.95)
smam_nrwd_nd_ci <- smam_nrwd_nd_ci1$conf.int
smam_nrwd_nd_ci_l <- smam_nrwd_nd_ci[1]
smam_nrwd_nd_ci_u <- smam_nrwd_nd_ci[2]

smam_nragb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$smam2==0])
smam_nragb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$smam2==0], sigma.x = 2, conf.level = 0.95)
smam_nragb_nd_ci_og <- smam_nragb_nd_ci1_og$conf.int
smam_nragb_nd_ci_og_l <- smam_nragb_nd_ci_og[1]
smam_nragb_nd_ci_og_u <- smam_nragb_nd_ci_og[2]

smam_nrd_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$smam2==0])
smam_nrd_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$smam2==0], sigma.x = 2, conf.level = 0.95)
smam_nrd_nd_ci_og <- smam_nrd_nd_ci1_og$conf.int
smam_nrd_nd_ci_og_l <- smam_nrd_nd_ci_og[1]
smam_nrd_nd_ci_og_u <- smam_nrd_nd_ci_og[2]

smam_nrwd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$smam2==0])
smam_nrwd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$smam2==0], sigma.x = 2, conf.level = 0.95)
smam_nrwd_nd_ci_og <- smam_nrwd_nd_ci1_og$conf.int
smam_nrwd_nd_ci_og_l <- smam_nrwd_nd_ci_og[1]
smam_nrwd_nd_ci_og_u <- smam_nrwd_nd_ci_og[2]

#ceph
ceph_nragb_nd <- mean(tree_dat_imputed$AGB[tree_dat_imputed$ceph2==0])
ceph_nragb_nd_ci1 <- t.test(tree_dat_imputed$AGB[tree_dat_imputed$ceph2==0], sigma.x = 2, conf.level = 0.95)
ceph_nragb_nd_ci <- ceph_nragb_nd_ci1$conf.int
ceph_nragb_nd_ci_l <- ceph_nragb_nd_ci[1]
ceph_nragb_nd_ci_u <- ceph_nragb_nd_ci[2]

ceph_nrd_nd <- mean(tree_dat_imputed$D[tree_dat_imputed$ceph2==0])
ceph_nrd_nd_ci1 <- t.test(tree_dat_imputed$D[tree_dat_imputed$ceph2==0], sigma.x = 2, conf.level = 0.95)
ceph_nrd_nd_ci <- ceph_nrd_nd_ci1$conf.int
ceph_nrd_nd_ci_l <- ceph_nrd_nd_ci[1]
ceph_nrd_nd_ci_u <- ceph_nrd_nd_ci[2]

ceph_nrwd_nd <- mean(tree_dat_imputed$meanWD[tree_dat_imputed$ceph2==0])
ceph_nrwd_nd_ci1 <- t.test(tree_dat_imputed$meanWD[tree_dat_imputed$ceph2==0], sigma.x = 2, conf.level = 0.95)
ceph_nrwd_nd_ci <- ceph_nrwd_nd_ci1$conf.int
ceph_nrwd_nd_ci_l <- ceph_nrwd_nd_ci[1]
ceph_nrwd_nd_ci_u <- ceph_nrwd_nd_ci[2]

ceph_nragb_nd_og <- mean(tree_dat_observed$AGB[tree_dat_observed$ceph2==0])
ceph_nragb_nd_ci1_og <- t.test(tree_dat_observed$AGB[tree_dat_observed$ceph2==0], sigma.x = 2, conf.level = 0.95)
ceph_nragb_nd_ci_og <- ceph_nragb_nd_ci1_og$conf.int
ceph_nragb_nd_ci_og_l <- ceph_nragb_nd_ci_og[1]
ceph_nragb_nd_ci_og_u <- ceph_nragb_nd_ci_og[2]

ceph_nrd_nd_og <- mean(tree_dat_observed$D[tree_dat_observed$ceph2==0])
ceph_nrd_nd_ci1_og <- t.test(tree_dat_observed$D[tree_dat_observed$ceph2==0], sigma.x = 2, conf.level = 0.95)
ceph_nrd_nd_ci_og <- ceph_nrd_nd_ci1_og$conf.int
ceph_nrd_nd_ci_og_l <- ceph_nrd_nd_ci_og[1]
ceph_nrd_nd_ci_og_u <- ceph_nrd_nd_ci_og[2]

ceph_nrwd_nd_og <- mean(tree_dat_observed$meanWD[tree_dat_observed$ceph2==0])
ceph_nrwd_nd_ci1_og <- t.test(tree_dat_observed$meanWD[tree_dat_observed$ceph2==0], sigma.x = 2, conf.level = 0.95)
ceph_nrwd_nd_ci_og <- ceph_nrwd_nd_ci1_og$conf.int
ceph_nrwd_nd_ci_og_l <- ceph_nrwd_nd_ci_og[1]
ceph_nrwd_nd_ci_og_u <- ceph_nrwd_nd_ci_og[2]

```


```{r}
#Compensation
avg <- c(total_agb, total_d, total_wd, total_agb_og, total_d_og, total_wd_og,
        ele_agb, ele_d, ele_wd, ele_agb_og, ele_d_og, ele_wd_og,
        ape_agb, ape_d, ape_wd, ape_agb_og, ape_d_og, ape_wd_og,
        monkey_agb, monkey_d, monkey_wd, monkey_agb_og, monkey_d_og, monkey_wd_og,
        smam_agb, smam_d, smam_wd, smam_agb_og, smam_d_og, smam_wd_og,
        ceph_agb, ceph_d, ceph_wd, ceph_agb_og, ceph_d_og, ceph_wd_og,
        
        
        total_agb_nd, total_d_nd, total_wd_nd, total_agb_nd_og, total_d_nd_og, total_wd_nd_og,
        ele_agb_nd, ele_d_nd, ele_wd_nd, ele_agb_nd_og, ele_d_nd_og, ele_wd_nd_og,
        ape_agb_nd, ape_d_nd, ape_wd_nd, ape_agb_nd_og, ape_d_nd_og, ape_wd_nd_og,
        monkey_agb_nd, monkey_d_nd, monkey_wd_nd, monkey_agb_nd_og, monkey_d_nd_og, monkey_wd_nd_og,
        smam_agb_nd, smam_d_nd, smam_wd_nd, smam_agb_nd_og, smam_d_nd_og, smam_wd_nd_og,
        ceph_agb_nd, ceph_d_nd, ceph_wd_nd, ceph_agb_nd_og, ceph_d_nd_og, ceph_wd_nd_og
        
        )

ci_l <- c(total_agb_ci_l, total_d_ci_l, total_wd_ci_l, total_agb_ci_og_l, total_d_ci_og_l, total_wd_ci_og_l,
        ele_agb_ci_l, ele_d_ci_l, ele_wd_ci_l, ele_agb_ci_og_l, ele_d_ci_og_l, ele_wd_ci_og_l,
        ape_agb_ci_l, ape_d_ci_l, ape_wd_ci_l, ape_agb_ci_og_l, ape_d_ci_og_l, ape_wd_ci_og_l,
        monkey_agb_ci_l, monkey_d_ci_l, monkey_wd_ci_l, monkey_agb_ci_og_l, monkey_d_ci_og_l, monkey_wd_ci_og_l,
        smam_agb_ci_l, smam_d_ci_l, smam_wd_ci_l, smam_agb_ci_og_l, smam_d_ci_og_l, smam_wd_ci_og_l,
        ceph_agb_ci_l, ceph_d_ci_l, ceph_wd_ci_l, ceph_agb_ci_og_l, ceph_d_ci_og_l, ceph_wd_ci_og_l,
        
        
        total_agb_nd_ci_l, total_d_nd_ci_l, total_wd_nd_ci_l, total_agb_nd_ci_og_l, total_d_nd_ci_og_l, total_wd_nd_ci_og_l,
        ele_agb_nd_ci_l, ele_d_nd_ci_l, ele_wd_nd_ci_l, ele_agb_nd_ci_og_l, ele_d_nd_ci_og_l, ele_wd_nd_ci_og_l,
        ape_agb_nd_ci_l, ape_d_nd_ci_l, ape_wd_nd_ci_l, ape_agb_nd_ci_og_l, ape_d_nd_ci_og_l, ape_wd_nd_ci_og_l,
        monkey_agb_nd_ci_l, monkey_d_nd_ci_l, monkey_wd_nd_ci_l, monkey_agb_nd_ci_og_l, monkey_d_nd_ci_og_l, monkey_wd_nd_ci_og_l,
        smam_agb_nd_ci_l, smam_d_nd_ci_l, smam_wd_nd_ci_l, smam_agb_nd_ci_og_l, smam_d_nd_ci_og_l, smam_wd_nd_ci_og_l,
        ceph_agb_nd_ci_l, ceph_d_nd_ci_l, ceph_wd_nd_ci_l, ceph_agb_nd_ci_og_l, ceph_d_nd_ci_og_l, ceph_wd_nd_ci_og_l
        )

ci_u <- c(total_agb_ci_u, total_d_ci_u, total_wd_ci_u, total_agb_ci_og_u, total_d_ci_og_u, total_wd_ci_og_u,
        ele_agb_ci_u, ele_d_ci_u, ele_wd_ci_u, ele_agb_ci_og_u, ele_d_ci_og_u, ele_wd_ci_og_u,
        ape_agb_ci_u, ape_d_ci_u, ape_wd_ci_u, ape_agb_ci_og_u, ape_d_ci_og_u, ape_wd_ci_og_u,
        monkey_agb_ci_u, monkey_d_ci_u, monkey_wd_ci_u, monkey_agb_ci_og_u, monkey_d_ci_og_u, monkey_wd_ci_og_u,
        smam_agb_ci_u, smam_d_ci_u, smam_wd_ci_u, smam_agb_ci_og_u, smam_d_ci_og_u, smam_wd_ci_og_u,
        ceph_agb_ci_u, ceph_d_ci_u, ceph_wd_ci_u, ceph_agb_ci_og_u, ceph_d_ci_og_u, ceph_wd_ci_og_u,
        
        
        total_agb_nd_ci_u, total_d_nd_ci_u, total_wd_nd_ci_u, total_agb_nd_ci_og_u, total_d_nd_ci_og_u, total_wd_nd_ci_og_u,
        ele_agb_nd_ci_u, ele_d_nd_ci_u, ele_wd_nd_ci_u, ele_agb_nd_ci_og_u, ele_d_nd_ci_og_u, ele_wd_nd_ci_og_u,
        ape_agb_nd_ci_u, ape_d_nd_ci_u, ape_wd_nd_ci_u, ape_agb_nd_ci_og_u, ape_d_nd_ci_og_u, ape_wd_nd_ci_og_u,
        monkey_agb_nd_ci_u, monkey_d_nd_ci_u, monkey_wd_nd_ci_u, monkey_agb_nd_ci_og_u, monkey_d_nd_ci_og_u, monkey_wd_nd_ci_og_u,
        smam_agb_nd_ci_u, smam_d_nd_ci_u, smam_wd_nd_ci_u, smam_agb_nd_ci_og_u, smam_d_nd_ci_og_u, smam_wd_nd_ci_og_u,
        ceph_agb_nd_ci_u, ceph_d_nd_ci_u, ceph_wd_nd_ci_u, ceph_agb_nd_ci_og_u, ceph_d_nd_ci_og_u, ceph_wd_nd_ci_og_u
        )

taxa <- c("total", "total", "total", "total", "total", "total",
          "elephant", "elephant","elephant", "elephant","elephant", "elephant",
          "ape", "ape", "ape", "ape", "ape", "ape",
          "monkey", "monkey", "monkey", "monkey","monkey", "monkey",
          "small_mammal","small_mammal","small_mammal","small_mammal","small_mammal","small_mammal",
          "duiker","duiker","duiker","duiker","duiker","duiker",
          "total", "total", "total", "total", "total", "total",
          "elephant", "elephant","elephant", "elephant","elephant", "elephant",
          "ape", "ape", "ape", "ape", "ape", "ape",
          "monkey", "monkey", "monkey", "monkey","monkey", "monkey",
          "small_mammal","small_mammal","small_mammal","small_mammal","small_mammal","small_mammal",
          "duiker","duiker","duiker","duiker","duiker","duiker"
          )

variable <- c("agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd"
             )

network <- c("imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original"
             )

dispersed <- rep(c("yes","no"), each=36)

dispersed_plants <- as.data.frame(cbind(avg, ci_l, ci_u, taxa, variable, network, dispersed))
dispersed_plants$avg <- as.numeric(dispersed_plants$avg)
dispersed_plants$ci_l <- as.numeric(dispersed_plants$ci_l)
dispersed_plants$ci_u <- as.numeric(dispersed_plants$ci_u)

#No Compensation

avg_nr <- c(total_nr_agb, total_nr_d, total_nr_wd, total_nr_agb_og, total_nr_d_og, total_nr_wd_og,
        ele_nragb, ele_nrd, ele_nrwd, ele_nragb_og, ele_nrd_og, ele_nrwd_og,
        ape_nragb, ape_nrd, ape_nrwd, ape_nragb_og, ape_nrd_og, ape_nrwd_og,
        monkey_nragb, monkey_nrd, monkey_nrwd, monkey_nragb_og, monkey_nrd_og, monkey_nrwd_og,
        smam_nragb, smam_nrd, smam_nrwd, smam_nragb_og, smam_nrd_og, smam_nrwd_og,
        ceph_nragb, ceph_nrd, ceph_nrwd, ceph_nragb_og, ceph_nrd_og, ceph_nrwd_og,
        
        
        total_nragb_nd, total_nrd_nd, total_nrwd_nd, total_nragb_nd_og, total_nrd_nd_og, total_nrwd_nd_og,
        ele_nragb_nd, ele_nrd_nd, ele_nrwd_nd, ele_nragb_nd_og, ele_nrd_nd_og, ele_nrwd_nd_og,
        ape_nragb_nd, ape_nrd_nd, ape_nrwd_nd, ape_nragb_nd_og, ape_nrd_nd_og, ape_nrwd_nd_og,
        monkey_nragb_nd, monkey_nrd_nd, monkey_nrwd_nd, monkey_nragb_nd_og, monkey_nrd_nd_og, monkey_nrwd_nd_og,
        smam_nragb_nd, smam_nrd_nd, smam_nrwd_nd, smam_nragb_nd_og, smam_nrd_nd_og, smam_nrwd_nd_og,
        ceph_nragb_nd, ceph_nrd_nd, ceph_nrwd_nd, ceph_nragb_nd_og, ceph_nrd_nd_og, ceph_nrwd_nd_og
        
        )

ci_l_nr <- c(total_nr_agb_ci_l, total_nr_d_ci_l, total_nr_wd_ci_l, total_nr_agb_ci_og_l, total_nr_d_ci_og_l, total_nr_wd_ci_og_l,
        ele_nragb_ci_l, ele_nrd_ci_l, ele_nrwd_ci_l, ele_nragb_ci_og_l, ele_nrd_ci_og_l, ele_nrwd_ci_og_l,
        ape_nragb_ci_l, ape_nrd_ci_l, ape_nrwd_ci_l, ape_nragb_ci_og_l, ape_nrd_ci_og_l, ape_nrwd_ci_og_l,
        monkey_nragb_ci_l, monkey_nrd_ci_l, monkey_nrwd_ci_l, monkey_nragb_ci_og_l, monkey_nrd_ci_og_l, monkey_nrwd_ci_og_l,
        smam_nragb_ci_l, smam_nrd_ci_l, smam_nrwd_ci_l, smam_nragb_ci_og_l, smam_nrd_ci_og_l, smam_nrwd_ci_og_l,
        ceph_nragb_ci_l, ceph_nrd_ci_l, ceph_nrwd_ci_l, ceph_nragb_ci_og_l, ceph_nrd_ci_og_l, ceph_nrwd_ci_og_l,
        
        
        total_nragb_nd_ci_l, total_nrd_nd_ci_l, total_nrwd_nd_ci_l, total_nragb_nd_ci_og_l, total_nrd_nd_ci_og_l, total_nrwd_nd_ci_og_l,
        ele_nragb_nd_ci_l, ele_nrd_nd_ci_l, ele_nrwd_nd_ci_l, ele_nragb_nd_ci_og_l, ele_nrd_nd_ci_og_l, ele_nrwd_nd_ci_og_l,
        ape_nragb_nd_ci_l, ape_nrd_nd_ci_l, ape_nrwd_nd_ci_l, ape_nragb_nd_ci_og_l, ape_nrd_nd_ci_og_l, ape_nrwd_nd_ci_og_l,
        monkey_nragb_nd_ci_l, monkey_nrd_nd_ci_l, monkey_nrwd_nd_ci_l, monkey_nragb_nd_ci_og_l, monkey_nrd_nd_ci_og_l, monkey_nrwd_nd_ci_og_l,
        smam_nragb_nd_ci_l, smam_nrd_nd_ci_l, smam_nrwd_nd_ci_l, smam_nragb_nd_ci_og_l, smam_nrd_nd_ci_og_l, smam_nrwd_nd_ci_og_l,
        ceph_nragb_nd_ci_l, ceph_nrd_nd_ci_l, ceph_nrwd_nd_ci_l, ceph_nragb_nd_ci_og_l, ceph_nrd_nd_ci_og_l, ceph_nrwd_nd_ci_og_l
        )

ci_u_nr <- c(total_nr_agb_ci_u, total_nr_d_ci_u, total_nr_wd_ci_u, total_nr_agb_ci_og_u, total_nr_d_ci_og_u, total_nr_wd_ci_og_u,
        ele_nragb_ci_u, ele_nrd_ci_u, ele_nrwd_ci_u, ele_nragb_ci_og_u, ele_nrd_ci_og_u, ele_nrwd_ci_og_u,
        ape_nragb_ci_u, ape_nrd_ci_u, ape_nrwd_ci_u, ape_nragb_ci_og_u, ape_nrd_ci_og_u, ape_nrwd_ci_og_u,
        monkey_nragb_ci_u, monkey_nrd_ci_u, monkey_nrwd_ci_u, monkey_nragb_ci_og_u, monkey_nrd_ci_og_u, monkey_nrwd_ci_og_u,
        smam_nragb_ci_u, smam_nrd_ci_u, smam_nrwd_ci_u, smam_nragb_ci_og_u, smam_nrd_ci_og_u, smam_nrwd_ci_og_u,
        ceph_nragb_ci_u, ceph_nrd_ci_u, ceph_nrwd_ci_u, ceph_nragb_ci_og_u, ceph_nrd_ci_og_u, ceph_nrwd_ci_og_u,
        
        
        total_nragb_nd_ci_u, total_nrd_nd_ci_u, total_nrwd_nd_ci_u, total_nragb_nd_ci_og_u, total_nrd_nd_ci_og_u, total_nrwd_nd_ci_og_u,
        ele_nragb_nd_ci_u, ele_nrd_nd_ci_u, ele_nrwd_nd_ci_u, ele_nragb_nd_ci_og_u, ele_nrd_nd_ci_og_u, ele_nrwd_nd_ci_og_u,
        ape_nragb_nd_ci_u, ape_nrd_nd_ci_u, ape_nrwd_nd_ci_u, ape_nragb_nd_ci_og_u, ape_nrd_nd_ci_og_u, ape_nrwd_nd_ci_og_u,
        monkey_nragb_nd_ci_u, monkey_nrd_nd_ci_u, monkey_nrwd_nd_ci_u, monkey_nragb_nd_ci_og_u, monkey_nrd_nd_ci_og_u, monkey_nrwd_nd_ci_og_u,
        smam_nragb_nd_ci_u, smam_nrd_nd_ci_u, smam_nrwd_nd_ci_u, smam_nragb_nd_ci_og_u, smam_nrd_nd_ci_og_u, smam_nrwd_nd_ci_og_u,
        ceph_nragb_nd_ci_u, ceph_nrd_nd_ci_u, ceph_nrwd_nd_ci_u, ceph_nragb_nd_ci_og_u, ceph_nrd_nd_ci_og_u, ceph_nrwd_nd_ci_og_u
        )

taxa_nr <- c("total", "total", "total", "total", "total", "total",
          "elephant", "elephant","elephant", "elephant","elephant", "elephant",
          "ape", "ape", "ape", "ape", "ape", "ape",
          "monkey", "monkey", "monkey", "monkey","monkey", "monkey",
          "small_mammal","small_mammal","small_mammal","small_mammal","small_mammal","small_mammal",
          "duiker","duiker","duiker","duiker","duiker","duiker",
          "total", "total", "total", "total", "total", "total",
          "elephant", "elephant","elephant", "elephant","elephant", "elephant",
          "ape", "ape", "ape", "ape", "ape", "ape",
          "monkey", "monkey", "monkey", "monkey","monkey", "monkey",
          "small_mammal","small_mammal","small_mammal","small_mammal","small_mammal","small_mammal",
          "duiker","duiker","duiker","duiker","duiker","duiker"
          )

variable_nr <- c("agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd",
             "agb", "d", "wd", "agb", "d", "wd"
             )

network_nr <- c("imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original",
             "imputed", "imputed","imputed", "original", "original", "original"
             )

dispersed_nr <- rep(c("yes","no"), each=36)

dispersed_plants_nr <- as.data.frame(cbind(avg_nr, ci_l_nr, ci_u_nr, taxa_nr, variable_nr, network_nr, dispersed_nr))
dispersed_plants_nr$avg_nr <- as.numeric(dispersed_plants_nr$avg_nr)
dispersed_plants_nr$ci_l_nr <- as.numeric(dispersed_plants_nr$ci_l_nr)
dispersed_plants_nr$ci_u_nr <- as.numeric(dispersed_plants_nr$ci_u_nr)
colnames(dispersed_plants_nr) <- colnames(dispersed_plants)



dispersed_plants$taxa[dispersed_plants$taxa=="total"] <- "Total"
dispersed_plants$taxa[dispersed_plants$taxa=="small_mammal"] <- "Rodent"
dispersed_plants$taxa[dispersed_plants$taxa=="monkey"] <- "Monkey"
dispersed_plants$taxa[dispersed_plants$taxa=="elephant"] <- "Elephant"
dispersed_plants$taxa[dispersed_plants$taxa=="duiker"] <- "Duiker"
dispersed_plants$taxa[dispersed_plants$taxa=="ape"] <- "Ape"
dispersed_plants$taxa <- fct_relevel(dispersed_plants$taxa, c("Rodent", "Duiker","Monkey","Ape", "Elephant","Total"))
dispersed_plants <- dispersed_plants %>% rename(Network=network, Dispersed=dispersed)
dispersed_plants$Network[dispersed_plants$Network=="imputed"] <- "Imputed"
dispersed_plants$Network[dispersed_plants$Network=="original"] <- "Observed"
dispersed_plants$Dispersed[dispersed_plants$Dispersed=="yes"] <- "Yes"
dispersed_plants$Dispersed[dispersed_plants$Dispersed=="no"] <- "No"

dispersed_plants_nr$taxa[dispersed_plants_nr$taxa=="total"] <- "Total"
dispersed_plants_nr$taxa[dispersed_plants_nr$taxa=="small_mammal"] <- "Rodent"
dispersed_plants_nr$taxa[dispersed_plants_nr$taxa=="monkey"] <- "Monkey"
dispersed_plants_nr$taxa[dispersed_plants_nr$taxa=="elephant"] <- "Elephant"
dispersed_plants_nr$taxa[dispersed_plants_nr$taxa=="duiker"] <- "Duiker"
dispersed_plants_nr$taxa[dispersed_plants_nr$taxa=="ape"] <- "Ape"
dispersed_plants_nr$taxa <- fct_relevel(dispersed_plants_nr$taxa, c("Rodent", "Duiker","Monkey","Ape", "Elephant","Total"))
dispersed_plants_nr <- dispersed_plants_nr %>% rename(Network=network, Dispersed=dispersed)
dispersed_plants_nr$Network[dispersed_plants_nr$Network=="imputed"] <- "Imputed"
dispersed_plants_nr$Network[dispersed_plants_nr$Network=="original"] <- "Observed"
dispersed_plants_nr$Dispersed[dispersed_plants_nr$Dispersed=="yes"] <- "Yes"
dispersed_plants_nr$Dispersed[dispersed_plants_nr$Dispersed=="no"] <- "No"

dispersed_plants_nr$Network[dispersed_plants_nr$Network=="Imputed"] <- "Imputed, No Compensation"
dispersed_plants_nr$Network[dispersed_plants_nr$Network=="Observed"] <- "Observed, No Compensation"
dispersed_plants_nr$Network[dispersed_plants$Network=="Imputed"] <- "Imputed, Compensation"
dispersed_plants_nr$Network[dispersed_plants$Network=="Observed"] <- "Observed, Compensation"

dispersed_plants_total <- rbind(dispersed_plants_nr, dispersed_plants)

```


```{r}


agb <- ggplot(data=dispersed_plants[dispersed_plants$variable=="agb",], aes(x=avg, y=taxa, color=Network, linetype=Dispersed))+
  geom_point(size=1,position=position_dodge(0.5))+
   geom_errorbar(aes(xmin =ci_l, xmax = ci_u), size=0.5, width =0.7, 
                 position=position_dodge(0.5))+
  theme_classic()+
  xlab("AGB (Mg)")+
  ylab("Taxa")+
  scale_color_manual(values=c("deepskyblue3", "grey50", "deepskyblue", "grey80"))+
  theme(text = element_text(size = 15)) 

wd <- ggplot(data=dispersed_plants[dispersed_plants$variable=="wd",], aes(x=avg, y=taxa, color=Network, alpha=Dispersed))+
  geom_point(size=1,position=position_dodge(0.5))+
   geom_errorbar(aes(xmin =ci_l, xmax = ci_u), size=0.5, width =0.7, 
                 position=position_dodge(0.5))+
  theme_classic()+
  xlab("Wood Density (g/cm3)")+
  ylab("Taxa")+
  scale_color_manual(values=c("deepskyblue3", "grey50"))+
  theme(text = element_text(size = 15)) +
  scale_alpha_manual(values=c(0.4,1))+ theme(legend.position = "none")

d <- ggplot(data=dispersed_plants[dispersed_plants$variable=="d",], aes(x=avg, y=taxa, color=Network, alpha=Dispersed))+
  geom_point(size=1,position=position_dodge(0.5))+
   geom_errorbar(aes(xmin =ci_l, xmax = ci_u), size=0.5, width =0.7, 
                 position=position_dodge(0.5))+
  theme_classic()+
  xlab("DBH (cm)")+
  ylab("Taxa")+
  scale_color_manual(values=c("deepskyblue3", "grey50"))+
  theme(text = element_text(size = 15)) +
  scale_alpha_manual(values=c(0.4,1))+ theme(legend.position = "none")

ggarrange(agb, ggarrange(wd, d, ncol=2, labels=c("b", "c")), labels="a", nrow=2, common.legend = TRUE)

```


```{r}
tree_dat_observed2 <- tree_dat_observed %>% pivot_longer(cols = DispersedBinary:smam, names_to="Taxa", values_to="Interaction") %>% mutate(Model ="Observed") 
tree_dat_observed2$Interaction[tree_dat_observed2$Interaction==1] <- "ObservedDispersed"
tree_dat_observed2$Interaction[tree_dat_observed2$Interaction==0] <- "ObservedNotDispersed"
tree_dat_imputed2 <- tree_dat_imputed %>% pivot_longer(cols = DispersedBinary:smam, names_to="Taxa", values_to="Interaction") %>% mutate(Model ="Imputed")
tree_dat_imputed2$Interaction[tree_dat_imputed2$Interaction==1] <- "ImputedDispersed"
tree_dat_imputed2$Interaction[tree_dat_imputed2$Interaction==0] <- "ImputedNotDispersed"

tree_dat_observed_total <- tree_dat_observed2[tree_dat_observed2$Taxa=="DispersedBinary",]
total_obs_wd <- t.test(meanWD ~ Interaction,data=tree_dat_observed_total)
total_obs_agb <- t.test(AGB~ Interaction,data=tree_dat_observed_total)
total_obs_d <- t.test(D ~ Interaction,data=tree_dat_observed_total)
tree_dat_imputed_total <- tree_dat_imputed2[tree_dat_imputed2$Taxa=="DispersedBinary",]
total_imp_wd <- t.test(meanWD ~ Interaction,data=tree_dat_imputed_total)
total_imp_agb <- t.test(AGB~ Interaction,data=tree_dat_imputed_total)
total_imp_d <- t.test(D ~ Interaction,data=tree_dat_imputed_total)

```


```{r}
tree_dat_total <- rbind(tree_dat_observed2, tree_dat_imputed2)

tree.summary <- tree_dat_total %>%
  group_by(Taxa, Interaction) %>%
  summarise(
    sdWD = sd(meanWD, na.rm = TRUE),
    WD = mean(meanWD),
    sdD = sd(D, na.rm = TRUE),
    D = mean(D),
    sdAGB = sd(AGB, na.rm = TRUE),
    AGB = mean(AGB)
  ) %>% select(Taxa, Interaction, WD, sdWD, D, sdD, AGB, sdAGB)

tree.summary$Taxa[tree.summary$Taxa=="smam"] <- "Rodent"
tree.summary$Taxa[tree.summary$Taxa=="ceph"] <- "Duiker"
tree.summary$Taxa[tree.summary$Taxa=="ele"] <- "Elephant"
tree.summary$Taxa[tree.summary$Taxa=="DispersedBinary"] <- "Total"
tree.summary$Taxa[tree.summary$Taxa=="ape"] <- "Ape"
tree.summary$Taxa[tree.summary$Taxa=="monkey"] <- "Monkey"

tree.summary$Interaction[tree.summary$Interaction=="ImputedDispersed"] <- "Imputed, Dispersed"
tree.summary$Interaction[tree.summary$Interaction=="ObservedDispersed"] <- "Observed, Dispersed"
tree.summary$Interaction[tree.summary$Interaction=="ImputedNotDispersed"] <- "Imputed, Undispersed"
tree.summary$Interaction[tree.summary$Interaction=="ObservedNotDispersed"] <- "Observed, Undispersed"

tree.summary$WD <- round(tree.summary$WD, digits=2)
tree.summary$sdWD <- round(tree.summary$sdWD, digits=2)
tree.summary$D <- round(tree.summary$D, digits=2)
tree.summary$sdD <- round(tree.summary$sdD, digits=2)
tree.summary$AGB <- round(tree.summary$AGB, digits=2)
tree.summary$sdAGB <- round(tree.summary$sdAGB, digits=2)

tree.summary$WD <- paste0(tree.summary$WD," (", tree.summary$sdWD, ")")
tree.summary$D <- paste0(tree.summary$D," (", tree.summary$sdD, ")")
tree.summary$AGB <- paste0(tree.summary$AGB," (", tree.summary$sdAGB, ")")

tree.summary2 <- tree.summary %>% select(Taxa, Interaction, WD, D, AGB)

write.csv(tree.summary2, "SummaryOutputs/StandSummary.csv")

```


